# Generated by Django 2.2 on 2021-08-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
